# Generated by Django 5.2.6 on 2026-07-28 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('SMS', 'پیامک'), ('EMAIL', 'ایمیل'), ('NOTIFICATION', 'اعلان')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('is_success', models.BooleanField(default=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
