# Generated by Django 5.2.6 on 2026-07-26 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت\u200cشده'), ('PROCESSING', 'در حال آماده\u200cسازی'), ('SENT', 'ارسال\u200cشده'), ('DELIVERED', 'تحویل\u200cشده'), ('CANCELED', 'لغوشده')], default='PENDING', max_length=16)),
                ('address_snapshot', models.JSONField()),
                ('subtotal', models.PositiveBigIntegerField(default=0)),
                ('shipping_cost', models.PositiveBigIntegerField(default=0)),
                ('discount_amount', models.PositiveBigIntegerField(default=0)),
                ('total', models.PositiveBigIntegerField(default=0)),
                ('tracking_code', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=220)),
                ('unit_price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
