# Generated by Django 5.2.6 on 2026-07-27 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discountcode_order_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID', 'پرداخت\u200cشده'), ('PROCESSING', 'در حال آماده\u200cسازی'), ('SENT', 'ارسال\u200cشده'), ('DELIVERED', 'تحویل\u200cشده'), ('CANCELED', 'لغوشده')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='MOCK', max_length=30)),
                ('amount', models.PositiveBigIntegerField()),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('CREATED', 'ایجادشده'), ('PENDING', 'در انتظار پرداخت'), ('SUCCEEDED', 'موفق'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغوشده')], default='CREATED', max_length=12)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
