# Generated by Django 5.2.6 on 2026-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_variant_name_orderitem_variant_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_committed',
            field=models.BooleanField(default=False),
        ),
    ]
