# Generated by Django 5.2.6 on 2026-07-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_deliveryslot_expense_messagetemplate_shippingrule_and_more'),
        ('orders', '0009_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.deliveryslot'),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_paid_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_paid_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
