# Generated by Django 5.2.6 on 2026-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
