# Generated by Django 5.2.6 on 2026-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_homesection_ends_at_homesection_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
