# Generated by Django 5.2.6 on 2026-07-31 06:51

from django.db import migrations, models


def rename_default_brand(apps, schema_editor):
    SiteSetting = apps.get_model("catalog", "SiteSetting")
    HomeSection = apps.get_model("catalog", "HomeSection")
    SiteSetting.objects.filter(site_name="تک‌استور").update(site_name="فروشگاه 82")
    SiteSetting.objects.filter(
        seo_home_title="تک‌استور | فروشگاه تخصصی کالای دیجیتال"
    ).update(seo_home_title="فروشگاه 82 | فروشگاه تخصصی کالای دیجیتال")
    SiteSetting.objects.filter(
        footer_text="© ۱۴۰۵ تک‌استور · تمامی حقوق محفوظ است · طراحی و توسعه اختصاصی"
    ).update(
        footer_text="© ۱۴۰۵ فروشگاه 82 · تمامی حقوق محفوظ است · طراحی و توسعه اختصاصی"
    )
    HomeSection.objects.filter(
        key="featured", subtitle="انتخاب‌های محبوب تک‌استور"
    ).update(subtitle="انتخاب‌های محبوب فروشگاه 82")
    HomeSection.objects.filter(
        key="about", title="درباره تک‌استور"
    ).update(title="درباره فروشگاه 82")


def restore_default_brand(apps, schema_editor):
    SiteSetting = apps.get_model("catalog", "SiteSetting")
    HomeSection = apps.get_model("catalog", "HomeSection")
    SiteSetting.objects.filter(site_name="فروشگاه 82").update(site_name="تک‌استور")
    SiteSetting.objects.filter(
        seo_home_title="فروشگاه 82 | فروشگاه تخصصی کالای دیجیتال"
    ).update(seo_home_title="تک‌استور | فروشگاه تخصصی کالای دیجیتال")
    SiteSetting.objects.filter(
        footer_text="© ۱۴۰۵ فروشگاه 82 · تمامی حقوق محفوظ است · طراحی و توسعه اختصاصی"
    ).update(
        footer_text="© ۱۴۰۵ تک‌استور · تمامی حقوق محفوظ است · طراحی و توسعه اختصاصی"
    )
    HomeSection.objects.filter(
        key="featured", subtitle="انتخاب‌های محبوب فروشگاه 82"
    ).update(subtitle="انتخاب‌های محبوب تک‌استور")
    HomeSection.objects.filter(
        key="about", title="درباره فروشگاه 82"
    ).update(title="درباره تک‌استور")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_redirectrule_brand_seo_description_brand_seo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.CharField(default='© ۱۴۰۵ فروشگاه 82 · تمامی حقوق محفوظ است · طراحی و توسعه اختصاصی', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_home_title',
            field=models.CharField(default='فروشگاه 82 | فروشگاه تخصصی کالای دیجیتال', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='فروشگاه 82', max_length=120),
        ),
        migrations.RunPython(rename_default_brand, restore_default_brand),
    ]
