from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0039_category_gaming_image")]

    operations = [
        migrations.AddField(model_name="sitesetting", name="home_hero_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_hero_autoplay", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_hero_interval_seconds", field=models.PositiveSmallIntegerField(default=6)),
        migrations.AddField(model_name="sitesetting", name="home_hero_controls", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_quick_links_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_banners_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_categories_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_brands_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_recommendations_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_recommendations_title", field=models.CharField(default="👀 بازدیدهای اخیر و محصولات مشابه", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="home_services_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="home_laptop_title", field=models.CharField(default="لپ‌تاپ‌ها", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="home_laptop_subtitle", field=models.CharField(default="کار، دانشگاه و بازی", max_length=140)),
        migrations.AddField(model_name="sitesetting", name="home_components_title", field=models.CharField(default="قطعات حرفه‌ای", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="home_components_subtitle", field=models.CharField(default="ارتقای سیستم هوشمند", max_length=140)),
        migrations.AddField(model_name="sitesetting", name="home_gaming_title", field=models.CharField(default="دنیای گیمینگ", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="home_gaming_subtitle", field=models.CharField(default="تجهیزات منتخب گیمرها", max_length=140)),
        migrations.AddField(model_name="sitesetting", name="home_monitor_title", field=models.CharField(default="مانیتورها", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="home_monitor_subtitle", field=models.CharField(default="تصویر دقیق و حرفه‌ای", max_length=140)),
        migrations.AddField(model_name="sitesetting", name="home_audio_title", field=models.CharField(default="هدفون و صدا", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="home_audio_subtitle", field=models.CharField(default="تجربه صوتی فراگیر", max_length=140)),
        migrations.AddField(model_name="sitesetting", name="gaming_hero_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_hero_autoplay", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_hero_interval_seconds", field=models.PositiveSmallIntegerField(default=5)),
        migrations.AddField(model_name="sitesetting", name="gaming_hero_controls", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_heading_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_heading_kicker", field=models.CharField(default="🎮 GAMING ZONE", max_length=80)),
        migrations.AddField(model_name="sitesetting", name="gaming_heading_title", field=models.CharField(default="دنیای محصولات گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_heading_subtitle", field=models.CharField(default="تجهیزات منتخب برای گیمرهایی که سرعت، دقت و قدرت واقعی می‌خواهند.", max_length=320)),
        migrations.AddField(model_name="sitesetting", name="gaming_banners_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_categories_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_brands_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_deals_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_deals_title", field=models.CharField(default="پیشنهادهای ویژه گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_top_rated_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_top_rated_title", field=models.CharField(default="💎 پیشنهادهای منتخب گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_value_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_value_title", field=models.CharField(default="⚡ پیشنهادهای ویژه تجهیزات گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_best_sellers_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_best_sellers_title", field=models.CharField(default="🔥 محبوب‌ترین محصولات گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_newest_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_newest_title", field=models.CharField(default="⚡ جدیدترین تجهیزات گیمینگ", max_length=160)),
        migrations.AddField(model_name="sitesetting", name="gaming_catalog_enabled", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="sitesetting", name="gaming_catalog_title", field=models.CharField(default="فروشگاه محصولات گیمینگ", max_length=160)),
    ]
