# Generated by Django 5.2.6 on 2026-07-30 12:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('PURCHASE', 'خرید'), ('REVIEW', 'ثبت نظر'), ('REFERRAL', 'دعوت دوست'), ('PROFILE', 'تکمیل پروفایل')], max_length=12)),
                ('target', models.PositiveIntegerField(default=1)),
                ('reward_points', models.PositiveIntegerField(default=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loyaltysetting',
            name='point_expiry_days',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='loyaltysetting',
            name='referral_bonus',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='loyaltysetting',
            name='review_bonus',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='LoyaltyPointEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=180)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='accounts.loyaltyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_jti', models.CharField(max_length=80, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=140)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
